### ISSUE TITLE
Padding is incorrect

### ISSUE THREAD

**Issue by ayobuenavista** [dmaasland/lastpass-authenticator-export#13]
Tried running this recently and got the following error.

```
Traceback (most recent call last):
  File "lastpass-authenticator-export.py", line 191, in <module>
    main()
  File "lastpass-authenticator-export.py", line 186, in main
    mfa_data = decrypt_user_data(user_data, key)
  File "lastpass-authenticator-export.py", line 121, in decrypt_user_data
    plaintext = unpad(
  File "/.../local/lib/python3.8/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

No 2FA enabled.

**Comment by RobThree** [comment]
```cmd
python3 lastpass-authenticator-export.py -u xxx@yyy.nl -o 123456
Password: 🔑
Traceback (most recent call last):
  File "/Users/rob/Code/lastpass-authenticator-export/lastpass-authenticator-export.py", line 212, in <module>
    main()
  File "/Users/rob/Code/lastpass-authenticator-export/lastpass-authenticator-export.py", line 207, in main
    mfa_data = decrypt_user_data(user_data, key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rob/Code/lastpass-authenticator-export/lastpass-authenticator-export.py", line 120, in decrypt_user_data
    plaintext = unpad(
                ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

It seems LastPass has changed something recently. I based part of [my project](https://github.com/RobThree/2FACLIClient) on this code and - I don't have a specific date unfortunately - LastPass seems to have changed something. My current vault file is from aug. 21st so it worked then.

Do you happen to know what changed @dmaasland ?

Edit/Update: Hmmm, LastPass *did* change something - today! I don't think it's [just the number of PBKDF2 iterations](https://support.lastpass.com/s/document-item?language=en_US&bundleId=lastpass&topicId=LastPass/about-password-iterations.html&_LANG=enus). The number (600,000) is retrieved correctly from `iterations.php`. I have contacted them to ask IF something has changed, and if so, WHAT (hoping they're willing to answer).

**Comment by RobThree** [comment]
@ayobuenavista Try changing this:

```python
    plaintext = unpad(
        cipher.decrypt(ciphertext),
        AES.block_size
    )
```

To this:

```python
    plaintext = unpad(
        cipher.decrypt(ciphertext),
        AES.block_size,
        'pkcs7'
    )
```

And let us know if this fixes your problem.

**Comment by ayobuenavista** [comment]
It's been awhile, and since I've completely migrated out of LastPass already, I wouldn't be able to test this. Closing this issue now.

**Comment by peter-avila** [comment]
Not sure if I can re-open this, but I am having the same issue. I have migrated off of LastPass proper but still use the Authenticator app but would like to finally move. I have added the additional argument and it still occurs. I've tried  ‘pkcs7’, ‘iso7816’ and ‘x923’. The script finishes but there is no page to browse as nothing is written out to the nginx directory.

```
Traceback (most recent call last):
  File "//lastpass-authenticator-export.py", line 213, in <module>
    main()
  File "//lastpass-authenticator-export.py", line 208, in main
    mfa_data = decrypt_user_data(user_data, key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//lastpass-authenticator-export.py", line 120, in decrypt_user_data
    plaintext = unpad(
                ^^^^^^
  File "/opt/byebyelp/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
.
.
Export done, see result http://localhost:8080/export/export.html
.
.
```

**Comment by RobThree** [comment]
You may be interested in [my project](https://github.com/RobThree/2FACLIClient) which still works (just tested it to be sure nothing changed since I last used it a few days ago).

**Comment by peter-avila** [comment]
> You may be interested in [my project](https://github.com/RobThree/2FACLIClient) which still works (just tested it to be sure nothing changed since I last used it a few days ago).

Cool, I'll check it out, thanks. 

If I have time, I'll see if I can fix this issue as well and open a PR.

**Comment by peter-avila** [comment]
> You may be interested in [my project](https://github.com/RobThree/2FACLIClient) which still works (just tested it to be sure nothing changed since I last used it a few days ago).

Some Q's
- Can I use your app to reveal the original seed? With that, I can easily generate a QR code.
- Ideally, I would like to have the seeds so I can encrypt & back them up, possibly using a TOTP app that I can back up to a private cloud. Can I back up your app so it is portable? Perhaps the key & data file?

**Comment by RobThree** [comment]
> Can I use your app to reveal the original seed? With that, I can easily generate a QR code.

Yes, if you set a breakpoint around [here](https://github.com/RobThree/2FACLIClient/blob/3d59591d0d99036bcecbcc408b99d22119b87e86/2FA/Program.cs#L101) you should have all the data in `mfadata`; instead of saving it encrypted you could save it anyway you like.

> Ideally, I would like to have the seeds

That's what gets stored (+ some metadata). 

> so I can encrypt & back them up

2FAClient already does that

> Can I back up your app so it is portable? Perhaps the key & data file?

The app is portable (and cross platform). That OTP data can just be copied anywhere. The key (I assume you're referring to the password to unlock the OTP data) is stored nowhere but in your head I hope 😉

**Comment by peter-avila** [comment]
> > Can I use your app to reveal the original seed? With that, I can easily generate a QR code.
> 
> Yes, if you set a breakpoint around [here](https://github.com/RobThree/2FACLIClient/blob/3d59591d0d99036bcecbcc408b99d22119b87e86/2FA/Program.cs#L101) you should have all the data in `mfadata`; instead of saving it encrypted you could save it anyway you like.
> 
> > Ideally, I would like to have the seeds
> 
> That's what gets stored (+ some metadata).
> 
> > so I can encrypt & back them up
> 
> 2FAClient already does that
> 
> > Can I back up your app so it is portable? Perhaps the key & data file?
> 
> The app is portable (and cross platform). That OTP data can just be copied anywhere. The key (I assume you're referring to the password to unlock the OTP data) is stored nowhere but in your head I hope 😉

Thanks. It all sounds great. 

I was referring to the encryption key to the locally stored data. I was just thinking about ways I could automate the backup (i.e., rsync, etc.).
