### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ssullivan** [dmaasland/lastpass-authenticator-export#15]
I've recently wanted switch out of LastPass and discovered they didn't have this functionality and this script really saved the day.

**Comment by nerdius** [comment]
This script is so handy! The way it works (using the audit interface) is ingenious!

I have a rooted device, and I even copied the SQLite database from the Authenticator app and dumped its contents, but decrypting the tokens proved to be tricky. (Another reason not to use anything from LastPass.) Fortunately, I didn't need to thanks to this script.

@dmaasland, thank you so much!
