### ISSUE TITLE
Login failed with OTP

### ISSUE THREAD

**Issue by ridhoperdana** [dmaasland/lastpass-authenticator-export#18]
Hi, thank you for the awesome script. But I have problem.

My account is using OTP which provided with the lastpass authenticator. I tried to login with the script, put the OTP from authenticator, and then put my password. The script returned:
```
Login failed!
<response><error message="Try again OR look for an email from LastPass to verify it&apos;s you." cause="unifiedloginresult" email="my email" is_passwordless_login="" passwordless_device_id=""  /></response>
```

Am I missing something? Thanks!

**Comment by ridhoperdana** [comment]
Solved, it turns out it was because I did not disable email verification to a new login from new location

**Comment by ikwyl6** [comment]
In case people cannot find this..Log into lastpass.com in web browser:
* Go to 'Account Settings'
* General tab
* At bottom of screen select 'Show Advanced Settings'
* Under 'Security' header you see 'Don't require email verification from unknown devices and locations.'
