### ISSUE TITLE
Sign in fails using username and otp

### ISSUE THREAD

**Issue by nate2014jatc** [dmaasland/lastpass-authenticator-export#3]
When signing in I receive the following error:

```
Login Failed!
<response><error iterations="5000" /></response>
```

This was solved by changing the "Iterations" amount in the Lastpass Account Advanced settings to their recommended value of "100100"

**Comment by dmaasland** [comment]
For what it's worth, I added a default iteration count of 5000 should LastPass return none. Thanks!

**Comment by nate2014jatc** [comment]
Thank you for your marvelous work, which allowed me to finally ditch that garbage company!
