### ISSUE TITLE
Keep getting a "Login failed" error

### ISSUE THREAD

**Issue by SuperSonicHub1** [dmaasland/lastpass-authenticator-export#4]
I am for sure typing out my password correctly and properly typing in my email and OTP, but I still get a login failed error. Looking through your code, I can see that you print out the text of the login response, but there is none. Is that supposed to happen?

**Comment by ikwyl6** [comment]
I had the same issue. I think it may be the TOTP, when enabled, is throwing the failed part. I haven’t had a chance to test it and remove 2FA on last pass website and then try it again. If you can do that, can you report back if that is the case (need to add ability to interact with 2FA)..

If that’s the case then maybe all that needs to be done for this script is ask user for OTP/TOTP and enter it like the lastpass-API: https://github.com/konomae/lastpass-python/blob/master/lastpass/fetcher.py

Also see #3

**Comment by dmaasland** [comment]
Ah, hmm. It seems LastPass doesn't always return the iteration count. Could you do a ```git pull``` and try again?

**Comment by SuperSonicHub1** [comment]
Still having the same error.

**Comment by dmaasland** [comment]
Hmm, I can't really reproduce that issue so that makes it hard for me to debug. Does it help when you change your iterations to 100100? 

https://support.logmeininc.com/lastpass/help/how-do-i-change-my-password-iterations-for-lastpass

**Comment by SuperSonicHub1** [comment]
No, it doesn't. I checked my LastPass account--my number of iterations
is 100100--and edited the iterations function to return 100100, and it
still doesn't work.

**Comment by dmaasland** [comment]
Have you configured any kind of special 2FA provider and / or other logon restrictions?

**Comment by SuperSonicHub1** [comment]
Nope, I just use LastPass Authenticator.

**Comment by ikwyl6** [comment]
@dmaasland  is there a way to do a print some variables to see what else is going on..? I know there is authenticator (https://pypi.org/project/authenticator/) that interfaces with 2fa for LP. Would this make sense to try to incorporate if this is the case..?
Or are you saying that you can run this script no problems without inputting your OTP? And do you have the TOTP/OTP enabled on the LP website for your account?

**Comment by dmaasland** [comment]
Yep, works for me without any issues. That's why I can't really debug. My guess would be that there is some setting you need to change when it comes to new / trusted devices or locations or whatever but I can't be sure. You could try adding some debug statements on line 78, like:

print(r.headers)
print(r.content)

etc.

**Comment by ikwyl6** [comment]
To see some debug info, in the ```def interations(username)``` function I added in:
```
    print("r.text: " + r.text)
    print("status: " + str(r.status_code))
    print("r.text type: ", type(r.text))
    iterations = int(float(r.text))
```
which gives me:
```
r.text: 100100
status: 200
r.text type:  <class 'str'>
```
then in ```def login(username, password, otp=None)``` I added:
```
        print("r.text: ", r.text)
        print("r.headers: ", r.headers)
        print("r.content: ", r.content)
```
which gives me:
```
Login failed!
r.text:
r.headers:  {'Content-Length': '0', 'Server': 'LastPass', 'Date': 'Mon, 26 Jul 2021 12:38:43 GMT', 'Connection': 'close', 'Set-Cookie': 'REMOVED; Domain=.lastpass.com; Path=/; Expires=Tue, 26 Jul 2022 12:38:43 GMT; Max-Age=31536000; Secure, bm_sz=REMOVED; Domain=.lastpass.com; Path=/; Expires=Mon, 26 Jul 2021 16:38:43 GMT; Max-Age=14400'}
r.content:  b''
```
The 'REMOVED' part I replace the session cookies info....
@dmaasland if you add in these debug pieces, do you get similar/same info...?

**Comment by dmaasland** [comment]
Ok, so, I think I've found it. I used another newer account (that was still active) to test with and it gave me the same weird behaviour. I looked at the "lastpass-python" library and noticed that they recently added a special user-agent string to all of their requests:

https://github.com/konomae/lastpass-python/commit/e647f162990eb53608bdce29ac5a7c91308f979a

Turns out that LastPass actually gives you a different response if you don't set that username exactly. Luckily, changing a user-name isn't that hard.

Try again with the latest version and let me know if it works.

**Comment by SuperSonicHub1** [comment]
It works! Thanks for the assist, @dmaasland, and thank you for making such a useful tool that should really be in the app! Side note: I actually really liked Authenticator seeing as it allowed me to sync my passwords between my phone and tablet, but that stopped working about a year ago, so I've been desperately searching for a way out and I sure am glad I found you!
