### ISSUE TITLE
Script needs update to work.

### ISSUE THREAD

**Issue by RaidForums** [dmaasland/lastpass-authenticator-export#5]
When using the script provided as is right now you will get the following response in CLI.

1. python3 script.py -u email@example.com -o OTP
2. `Password:` (it prompts password and I enter it)
3. `Login failed!`
`<response><error server="lastpass.eu" message="Please update to the latest version of LastPass." /></response>`

**Comment by dmaasland** [comment]
Hmm I can't really reproduce the error. It just works for me. Are there any other people experiencing this?

**Comment by RaidForums** [comment]
> 
> 
> Hmm I can't really reproduce the error. It just works for me. Are there any other people experiencing this?

Well, it's because LastPass moves you to their .eu domain when you have a premium membership and you're from the EU.
All I had to do was switch the .com domain to .eu on the code and it seemed to work fine, thanks.
