### ISSUE TITLE
KeyError: 'userData'

### ISSUE THREAD

**Issue by cynicalsam** [dmaasland/lastpass-authenticator-export#7]
Hi, I am trying to export my MFA codes from lastpass using this script. I get an error below when trying to run it. Does anyone have any idea?

`Sam@Sams-MBP Desktop % python3 lastpass-authenticator-export.py -u *******@gmail.com
Password: 
Traceback (most recent call last):
  File "lastpass-authenticator-export.py", line 188, in <module>
    main()
  File "lastpass-authenticator-export.py", line 182, in main
    user_data = get_mfa_backup(session, csrf)
  File "lastpass-authenticator-export.py", line 108, in get_mfa_backup
    return r.json()['userData']
KeyError: 'userData'`

**Comment by akikanellis** [comment]
Do you have 2FA setup with Lastpass? If yes then try the following command instead:

```
python3 lastpass-authenticator-export.py -u <your-email-here> -o <your-current-2fa-code-here>
```

**Comment by Yennoah** [comment]
I have the same problem, no 2fa?
